<?php
namespace App;

class Country
{
    public static function list() {
        return array(
            'AT' => 'Austria',
            'AU' => 'Australia',
            'AR' => 'Argentina',
            'BS' => 'Bahamas',
            'BH' => 'Bahrain',
            'BE' => 'Belgium',
            'BM' => 'Bermuda',
            'BR' => 'Brazil',
            'CA' => 'Canada',
            'KY' => 'Cayman Islands',
            'CL' => 'Chile',
            'CN' => 'China',
            'CO' => 'Colombia',
            'CZ' => 'Czech Republic',
            'DJ' => 'Djibouti',
            'DK' => 'Denmark',
            'DO' => 'Dominican Republic',
            'EC' => 'Ecuador',
            'EG' => 'Egypt',
            'FI' => 'Finland',
            'FR' => 'France',
            'DE' => 'Germany',
            'GB' => 'Great Britain',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'HK' => 'Hong Kong',
            'HN' => 'Honduras',
            'IN' => 'India',
            'ID' => 'Indonesia',
            'IE' => 'Ireland',
            'IL' => 'Israel',
            'IT' => 'Italy',
            'JP' => 'Japan',
            'KW' => 'Kuwait',
            'LB' => 'Lebanon',
            'LU' => 'Luxembourg',
            'MY' => 'Malaysia',
            'MX' => 'Mexico',
            'MM' => 'Myanmar',
            'NA' => 'Namibia',
            'NZ' => 'New Zealand',
            'NI' => 'Nigeria',
            'NL' => 'Netherlands',
            'NO' => 'Norway',
            'OM' => 'Oman',
            'PA' => 'Panama',
            'PE' => 'Peru',
            'PH' => 'Philippines',
            'PL' => 'Poland',
            'PT' => 'Portugal',
            'QA' => 'Qatar',
            'RO' => 'Romania',
            'SA' => 'Saudi Arabia',
            'SG' => 'Singapore',
            'ZA' => 'South Africa',
            'KR' => 'South Korea',
            'ES' => 'Spain',
            'SE' => 'Sweden',
            'CH' => 'Switzerland',
            'TR' => 'Turkey',
            'TC' => 'Turks and Caicos',
            'TH' => 'Thailand',
            'AE' => 'United Arab Emirates',
            'UK' => 'United Kingdom',
            'US' => 'United States of America',
            'VE' => 'Venezuela',
            'VN' => 'Vietnam',
            'CY' => 'Wales'
        );
    }
}
